version: '3.1'

services:

  postgres:
    image: postgres:15.8-alpine3.20
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: body_balance
    ports:
      - "5432:5432"
