application:
  name: Authentication
  host: http://localhost

server:
  port: 8085

spring:
  datasource:
    url: jdbc:postgresql://localhost:5437/auth
    username : postgres
    password : password-auth
    driver-class-name : org.postgresql.Driver
  liquibase:
    change-log: db/changelog/db.changelog-master.xml
    enabled: true
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: false
#    hibernate:
#      ddl-auto : update

logging:
  config: auth/src/main/resources/log4j2.xml

#logging.level.org.hibernate.SQL=DEBUG
#logging.level.org.hibernate.type.descriptor.sql=TRACE

springdoc:
  swagger-ui:
    path: /swagger-ui