app:
  test:
    host : http://localhost # найти другой способ выводить эту информацию в консоль

server:
  port: 8082

spring:
  application:
    name : Media
  datasource:
    url: jdbc:postgresql://localhost:5435/media
    username : postgres
    password : password-media
    driver-class-name : org.postgresql.Driver
  liquibase:
    change-log: db/changelog/db.changelog-master.xml
    enabled: true
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: false
#    hibernate:
#      ddl-auto : update

logging:
  config: monitoring/src/main/resources/log4j2.xml

#logging.level.org.hibernate.SQL=DEBUG
#logging.level.org.hibernate.type.descriptor.sql=TRACE

springdoc:
  swagger-ui:
    path: /swagger-ui